### ISSUE TITLE
something is not ok with the graphics

### ISSUE THREAD

**Issue by attuska** [dougmencken/HeadOverHeels#23]
![kepernyokep 2018-03-05 23-14-14](https://user-images.githubusercontent.com/6311614/37002947-9efe8278-20cb-11e8-8427-785a681417dc.png)

**Comment by dougmencken** [comment]
And what is so “wrong” there? Looks fine to me, and on my side it is the same

![gra](https://user-images.githubusercontent.com/3457110/37023280-4a7dbb90-211d-11e8-8011-756bd04b27d4.png)

By teh way, commit SHAs aren’t turned to links in title of issue, so I mention it here e6b8f529aac1acdeb14a011ca0d6293005e37e0b

**Comment by attuska** [comment]
The background of various things, as well as the backgrounds of head and heels are brown. The background recorded things are alright.

**Comment by dougmencken** [comment]
is it about shadows ( tints, sombreado, árnyék )? there’s some problem with them, free ( movable, moving ) items don’t cast shadows on other free items #15

**Comment by attuska** [comment]
> is it about shadows ( tints, sombreado, árnyék )?

Yes.

**Comment by dougmencken** [comment]
I know about this problem, so let’s move anything about shadows to 15th issue
