### ISSUE TITLE
room scrolling

### ISSUE THREAD

**Issue by attuska** [dougmencken/HeadOverHeels#26]
When Head dies, you can't see him anymore, and the room is not scrollable

![screen](https://user-images.githubusercontent.com/6311614/37698257-211cec14-2ce2-11e8-8e2a-f0a2f25e1075.png)

> player "head" is now in room "blacktooth/blacktooth58.xml"
copy of player "head" with behavior "behavior of Head" is created to rebuild this room
[New Thread 0xa517db40 (LWP 16602)]
[New Thread 0x9395ab40 (LWP 16603)]
playing Ogg music/jail.ogg
[Thread 0x9395ab40 (LWP 16603) exited]
metamorphosis of data for item "head" to data of "bubbles" initiated by "collide with mortal item"
[Thread 0xa517db40 (LWP 16602) exited]
parse "/usr/share/headoverheels/map/blacktooth/blacktooth58.xml"
creation of behavior "behavior of disappearance on jump into" for grid item "brick2" at x=208 y=63 z=0 with orientation "nowhere"
creation of behavior "behavior of disappearance on jump into" for grid item "brick2" at x=0 y=191 z=0 with orientation "nowhere"
creation of behavior "behavior of conveyor" for grid item "conveyor-belt" at x=112 y=159 z=0 with orientation "north"
creation of behavior "behavior of conveyor" for grid item "conveyor-belt" at x=128 y=159 z=0 with orientation "east"
creation of behavior "behavior of conveyor" for grid item "conveyor-belt" at x=128 y=143 z=0 with orientation "east"
creation of behavior "behavior of detector" for free item "bomb" at x=146 y=93 z=24 with orientation "nowhere"
creation of behavior "behavior of detector" for free item "bomb" at x=98 y=189 z=24 with orientation "nowhere"
free item with coordinates 0, 9, 1 is absent
got player "head" who entered this room @ MapManager::rebuildRoom
player "head" is now in room "blacktooth/blacktooth58.xml"
copy of player "head" with behavior "behavior of Head" is created to rebuild this room
[New Thread 0xa517db40 (LWP 16604)]

![head](https://user-images.githubusercontent.com/6311614/37699109-32cec7d0-2ce6-11e8-9ae3-bdf4904e8bc3.png)

**Comment by dougmencken** [comment]
yep, I need to deal with movements of camera

yet you may use [ control ] + [ alt ] + [ numpad key ] to move camera manually at any time
numpad 4 moves it left, 6 moves right, 2 moves down, 8 moves up

**Comment by dougmencken** [comment]
it looks perfect, closing
