### ISSUE TITLE
Linux compilation error

### ISSUE THREAD

**Issue by attuska** [dougmencken/HeadOverHeels#38]
>In file included from Ism.cpp:2:
Ism.hpp: In function ‘std::string isomot::numberToString(int)’:
Ism.hpp:109:97: error: taking address of rvalue [-fpermissive]

**Comment by dougmencken** [comment]
Can you try the just-updated master?

**Comment by attuska** [comment]
Yes.
New error: 
>./configure: line 17909: syntax error near unexpected token `fi'
./configure: line 17909: `fi'

**Comment by dougmencken** [comment]
Try now, please

```
 --- a/configure.ac
+++ b/configure.ac
@@ -56,7 +56,7 @@ else if test x"$with_allegro4" = x"yes" -a x"$with_allegro5" = x"no" -a test x"$
         AC_MSG_NOTICE(building with allegro4)
 else if test x"$with_allegro4" = x"yes" -a x"$with_allegro5" = x"yes" -a test x"$with_allegro" = x"yes" ; then
         AC_MSG_ERROR(--with-allegro5 and --with-allegro4 are mutually exclusive)
-else if test x"$with_allegro" = x"no" ;
+else if test x"$with_allegro" = x"no" ; then
         AC_MSG_NOTICE(building without allegro libraries)
 fi

```

**Comment by attuska** [comment]
New error: ./configure: line 20419: syntax error: unexpected end of file

**Comment by attuska** [comment]
The commit https://github.com/dougmencken/HeadOverHeels/commit/f79776fd110a39737ce4449531392f47441542bd compiliert.
