### ISSUE TITLE
Heels can't pass from the second room

### ISSUE THREAD

**Issue by johna23-lab** [dougmencken/HeadOverHeels#42]
Hi! i complied without any issue the game and works great until i play with heels, he can't jump to the other rooms and gets stuck in the second room.

I made a gif with the possible issue
![hoh](https://github.com/dougmencken/HeadOverHeels/assets/84197353/aa979cba-30fd-4c05-8dd7-06cd77b2ce10)

**Comment by kiwifb** [comment]
After hacking my way around a bit and making Heels do high jumps (but I don't have logic quite right which makes things difficult later on when Heels do high jumps when he should not). I noticed that Heels is a bit under developed at the moment. He cannot grab the bag for example.
While, Head is more advanced, there are some bits that are not finished. When I shot donuts, it stays where I am shooting from and as no effect whatsoever.

**Comment by kiwifb** [comment]
OK, I totally fixed the highjump behavior. At https://github.com/dougmencken/HeadOverHeels/blob/master/src/behaviors/UserControlled.cpp#L193 it needs to be "behavior of spring leap" instead of "behavior of big leap for character".

**Comment by dougmencken** [comment]
sorry for the late response and thanks for finding this, and fixing,

and can you please propose a patch ?

**Comment by kiwifb** [comment]
I'll send a PR your way. I am trying to figure why Heels cannot take the handbag now.

**Comment by dougmencken** [comment]
>Heels cannot grab the bag

🤔 all the code for taking a tool (doughnut horn, handbag) is just

https://github.com/dougmencken/HeadOverHeels/blob/a9dd5a3e14b769755376a57d8ad21281b1881563/src/behaviors/Special.cpp#L232

the definition of which is

https://github.com/dougmencken/HeadOverHeels/blob/a9dd5a3e14b769755376a57d8ad21281b1881563/src/PlayerItem.cpp#L467
