### ISSUE TITLE
Firing donuts doesn't

### ISSUE THREAD

**Issue by kiwifb** [dougmencken/HeadOverHeels#46]
When I fire donuts, the ball just stays in place and do not interact with anything, it does not have any effect at all.

**Comment by dougmencken** [comment]
just a guess .... maybe

_getOriginalLabel()_ not _getLabel()_

here

https://github.com/dougmencken/HeadOverHeels/blob/a4b3801c4c191f4163be02a3da9940b5bcbf8009/src/behaviors/Doughnut.cpp#L83C81-L83C81

**Comment by kiwifb** [comment]
I'll try later this evening (NZ time), I am officially on the clock now. But things are really shaping up.

**Comment by dougmencken** [comment]
and here as well

https://github.com/dougmencken/HeadOverHeels/blob/a4b3801c4c191f4163be02a3da9940b5bcbf8009/src/behaviors/UserControlled.cpp#L409

“original” labels are (relatively) new concept, therefore may not be used wherewhen they are expected to

**Comment by dougmencken** [comment]
here's 🎥 the video showing how it currently is 👀

" _an example of Firing donuts doesn't_ "

![an example of Firing donuts doesn't](https://github.com/dougmencken/HeadOverHeels/assets/3457110/618abe58-d876-4a4d-8b45-5a35162ea2b9)

**Comment by kiwifb** [comment]
But how do you get that kind of screen with the map?

**Comment by dougmencken** [comment]
> But how do you get that kind of screen with the map?

for now, if you switch the backgrounds off, either in the video options, or in-game via [ alt ] + [ shift ] + [ b ], then these miniatures will be shown

and I really wish the automap, there’s already a key choice for "show map" in the keys menu (currently doing nothing)

**Comment by dougmencken** [comment]
( some time later )

> But how do you get that kind of screen with the map?

heh there's just the option in the video menu ! 😌

![the new option](https://github.com/dougmencken/HeadOverHeels/assets/3457110/6653909c-e571-4b43-96f6-64e9f2ab2312)

**Comment by dougmencken** [comment]
_" an example of Firing donuts do (move) "_

![wooo](https://github.com/dougmencken/HeadOverHeels/assets/3457110/1fa6287a-54ec-43e4-bff9-c6a3107c0208)

**Comment by dougmencken** [comment]
easy—peasy

https://github.com/dougmencken/HeadOverHeels/blob/2900b1086340c2a3ce3f7c77b4e537beb3b626f4/source/behaviors/UserControlled.cpp#L430

you close, okay?

**Comment by dougmencken** [comment]
easy—peasy

https://github.com/dougmencken/HeadOverHeels/blob/2900b1086340c2a3ce3f7c77b4e537beb3b626f4/source/behaviors/UserControlled.cpp#L430

@kiwifb you close, okay?

**Comment by kiwifb** [comment]
It does work! I will probably redo the file system location of the executable and data folder a bit better. It was definitely a band aid and there is a better way to do it if you are going to use the values at configure time.
