### ISSUE TITLE
Charlie the Dalek doesn’t drive the character above it

### ISSUE THREAD

**Issue by hendrikbez** [dougmencken/HeadOverHeels#66]
I have now tried to move head or heels on the head of a
![Screenshot_4](https://github.com/dougmencken/HeadOverHeels/assets/49644474/beb18055-228f-4550-8885-4ddb8b693d74)
n item to the other site, but when i move the item, head or heels falls of it.  It is in the marketplace
![fout](https://github.com/dougmencken/HeadOverHeels/assets/49644474/efae4a75-c236-41c2-8f5e-6063d1cfb10f)
![Screenshot_3](https://github.com/dougmencken/HeadOverHeels/assets/49644474/22a30968-a4b1-473e-a681-fa1daa3e7393)

**Comment by dougmencken** [comment]
I see the problem : the character gets dalek as a carrier in the game’s code well, but moving it via remote controls doesn’t move the guy above

However, for now I haven’t figured out how to solve it

**Comment by dougmencken** [comment]
yet I found the solution

**Comment by hendrikbez** [comment]
Thank you

Hendrik
